<?php

/**
 * @file
 * Contains source.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function source_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the source module.
    case 'help.page.source':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function source_theme() {
  $theme = [];
  $theme['source'] = [
    'render element' => 'elements',
    'file' => 'source.page.inc',
    'template' => 'source',
  ];
  $theme['source_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'source.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function source_theme_suggestions_source(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#source'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'source__' . $sanitized_view_mode;
  $suggestions[] = 'source__' . $entity->bundle();
  $suggestions[] = 'source__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'source__' . $entity->id();
  $suggestions[] = 'source__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
